export type Area = { slug:string; title:string; summary:string; intro:string; services:string[]; approach:string };
export type Lawyer = { slug:string; name:string; role:string; oab:string; areas:string[]; education:string[]; bio:string; publications:string[]; image?:string;};
export type Article = { slug:string; category:string; title:string; excerpt:string; date:string; authorSlug:string; readTime:string; body:string[] };

export const areas: Area[] = [
  { slug:'direito-tributario', title:'Direito Tributário', summary:'Assessoria e atuação em questões tributárias administrativas e judiciais.', intro:'Atuação jurídica em questões tributárias que exigem análise técnica, visão estratégica e compreensão do ambiente empresarial.', services:['Planejamento tributário','Análise de questões fiscais','Consultoria tributária','Recuperação de créditos','Processos administrativos','Processos judiciais','Análise de riscos tributários','Acompanhamento de mudanças legislativas'], approach:'Cada questão tributária é analisada considerando o contexto jurídico, econômico e operacional envolvido, com identificação de riscos, alternativas e caminhos juridicamente adequados.' },
  { slug:'direito-empresarial', title:'Direito Empresarial', summary:'Estratégias jurídicas alinhadas às necessidades e ao contexto de cada negócio.', intro:'Assessoria jurídica para decisões empresariais, estruturas societárias e situações que exigem integração entre direito e negócio.', services:['Consultoria empresarial','Questões societárias','Governança','Reorganizações','Negociações','Prevenção de conflitos'], approach:'A atuação considera os objetivos do negócio, os riscos envolvidos e as alternativas juridicamente disponíveis para cada decisão.' },
  { slug:'contratos', title:'Contratos', summary:'Análise, elaboração, negociação e revisão de instrumentos contratuais.', intro:'Estruturação contratual com atenção à clareza, alocação de riscos e aderência à operação das partes.', services:['Elaboração de contratos','Revisão contratual','Negociação','Contratos empresariais','Instrumentos de garantia','Gestão de riscos contratuais'], approach:'Os instrumentos são desenvolvidos a partir da realidade da operação, buscando clareza, coerência e previsibilidade jurídica.' },
  { slug:'contencioso', title:'Contencioso', summary:'Atuação técnica na condução de demandas judiciais e administrativas.', intro:'Condução estratégica de conflitos com análise de risco, definição de teses e acompanhamento próximo da evolução de cada demanda.', services:['Contencioso cível','Contencioso empresarial','Processos administrativos','Estratégia processual','Negociação e acordos','Gestão de carteira'], approach:'Cada demanda é analisada de forma individualizada, considerando fundamentos jurídicos, evidências, riscos e possíveis desdobramentos.' },
  { slug:'consultoria-juridica', title:'Consultoria Jurídica', summary:'Análise preventiva de questões jurídicas e identificação de alternativas.', intro:'Apoio jurídico contínuo para decisões que demandam prevenção, estruturação e avaliação de riscos.', services:['Pareceres','Consultas jurídicas','Mapeamento de riscos','Apoio a decisões','Políticas internas','Prevenção de litígios'], approach:'A consultoria transforma questões jurídicas em informações claras para apoiar decisões responsáveis e documentadas.' },
  { slug:'regulatorio', title:'Regulatório', summary:'Apoio jurídico em temas regulatórios e ambientes normativos complexos.', intro:'Assessoria em ambientes regulados, com acompanhamento de normas, riscos e obrigações aplicáveis às operações.', services:['Análise regulatória','Acompanhamento normativo','Consultas e pareceres','Mapeamento de obrigações','Apoio institucional'], approach:'O trabalho parte da leitura técnica da regulação e de seus impactos concretos sobre processos, produtos e decisões empresariais.' },
];

export const lawyers: Lawyer[] = [
  { slug:'adilson-furlani', name:'FURLANI, Adilson', image:'/equipe/adilson-furlani.jpg', role:'Sócio-Advogado', oab:'OAB/SP 53.8189', areas:['Direito Civil','Digital', 'Consumidor'], education:['Advogado, Bacharel em Direito — Universidade Paulista','Especialista em Sistemas de Informação, Segurança da Informação e Análises de Sistemas Informáticos'], bio:'Advogado com expertise única na intersecção entre Direito e Tecnologia. Minha formação multidisciplinar em Direito, Sistemas, Segurança da Informação e Geoprocessamento permite oferecer soluções jurídicas inovadoras e precisas. Atuo com Direito Civil, Digital e LGPD, compreendendo a tecnologia por trás da lei, e com Direito Imobiliário e Ambiental, utilizando análises de dados geoespaciais. Meu compromisso é traduzir a complexidade técnica e jurídica em estratégias claras e seguras para os meus clientes.', publications:['Reforma Tributária: principais pontos para empresas','Planejamento e segurança jurídica nas decisões empresariais'] },
  { slug:'daniela-pinheiros', name:'PINHEIROS, Daniela', image:'/equipe/daniela-pinheiros.jpg', role:'Consultora Jurídica', oab:'', areas:['Direito Empresarial','Contratos'], education:['Bacharel em Direito — Universidade Paulista, Psicanalista Clínica','Pós-graduação em Direito Civil, Processo Civil e Previdenciário'], bio:'Com formação em Direito pela Universidade Paulista (UNIP) e em Psicanálise, ofereço uma abordagem integrada que visa promover tanto a justiça quanto a saúde mental. Meu trabalho consiste em orientar para a proteção e defesa de direitos, contribuindo para uma sociedade mais justa, além de auxiliar no processo de autoconhecimento e na construção de relações mais saudáveis. A união dessas duas áreas me permite analisar cada caso a partir sob uma perspectiva completa, que considera tanto os aspectos legais quanto as dimensões subjetivas de cada cliente.', publications:['Cláusulas contratuais que merecem atenção','Governança e prevenção de conflitos societários'] },
  { slug:'pedro-almeida', name:'ALMEIDA, Pedro', role:'Analista Jurídico', oab:'', areas:['Contencioso','Consultoria Jurídica'], education:['Bacharel em Direito'], bio:'Atua na condução de demandas judiciais e administrativas, com foco em análise processual, organização de evidências e acompanhamento estratégico.', publications:['Decisões empresariais e análise jurídica preventiva'] },
];

export const articles: Article[] = [
  { slug:'reforma-tributaria-principais-pontos-empresas', category:'Tributário', title:'Reforma Tributária: principais pontos para empresas', excerpt:'Uma visão objetiva sobre temas que merecem acompanhamento na adaptação ao novo ambiente tributário.', date:'12 set. 2026', authorSlug:'joao-da-silva', readTime:'6 min', body:['A Reforma Tributária altera de forma relevante a lógica de tributação sobre o consumo e exige atenção das empresas durante o período de transição.','Mais do que acompanhar mudanças legislativas, é importante mapear os impactos sobre contratos, precificação, sistemas, processos internos e relacionamento com fornecedores e clientes.','A avaliação jurídica deve ser integrada às áreas financeira, fiscal e operacional, de modo que as decisões sejam tomadas com base em informações consistentes e atualizadas.','Este conteúdo possui caráter exclusivamente informativo e não constitui aconselhamento jurídico individualizado.'] },
  { slug:'analise-juridica-preventiva-decisoes-empresariais', category:'Empresarial', title:'Decisões empresariais e a importância da análise jurídica preventiva', excerpt:'Como a leitura antecipada de riscos pode apoiar decisões mais estruturadas.', date:'05 set. 2026', authorSlug:'pedro-almeida', readTime:'5 min', body:['A análise jurídica preventiva busca identificar riscos antes que eles se convertam em conflitos ou custos inesperados.','Em decisões empresariais relevantes, a participação jurídica desde as etapas iniciais pode contribuir para estruturar documentos, responsabilidades e mecanismos de prevenção de controvérsias.','A prevenção não elimina incertezas, mas permite que elas sejam identificadas e tratadas de maneira organizada.','Este conteúdo possui caráter exclusivamente informativo e não constitui aconselhamento jurídico individualizado.'] },
  { slug:'clausulas-contratuais-atencao-especial', category:'Contratos', title:'Cláusulas contratuais que merecem atenção especial', excerpt:'Pontos que ajudam a tornar a relação contratual mais clara e previsível.', date:'28 ago. 2026', authorSlug:'mariana-souza', readTime:'7 min', body:['Contratos eficientes devem refletir a operação real das partes e distribuir responsabilidades de forma compreensível.','Cláusulas sobre objeto, pagamento, responsabilidade, rescisão, confidencialidade e solução de conflitos costumam merecer atenção especial.','A qualidade de um contrato não depende apenas de sua extensão, mas da clareza com que antecipa situações relevantes para aquela relação.','Este conteúdo possui caráter exclusivamente informativo e não constitui aconselhamento jurídico individualizado.'] },
  {
  slug: 'inadimplencia-no-contrato-de-aluguel-como-reaver-o-imovel-de-forma-rapida',
  category: 'Direito Imobiliário',
  title: 'Inadimplência no contrato de aluguel - Como reaver o imóvel de forma rápida',
  excerpt: 'Uma análise sobre a inadimplência na locação de imóveis, a ação de despejo e os instrumentos jurídicos disponíveis ao locador para a retomada do imóvel.',
  date: '23 abr. 2023',
  authorSlug: 'adilson-furlani',
  readTime: '18 min',
  body: [
    'Introdução',
    '    A inadimplência em contratos de locação pode gerar dificuldades relevantes para o proprietário do imóvel, especialmente quando os aluguéis e outros encargos permanecem em atraso e o locatário continua ocupando o bem. Nessas situações, é importante compreender quais medidas podem ser adotadas para cobrança dos valores e eventual retomada do imóvel.',
    '    O problema envolve não apenas o pagamento do aluguel, mas também obrigações previstas no contrato, como encargos da locação, conservação do imóvel e, conforme o caso, regularização de contas vinculadas à utilização da propriedade.',
    '1. Do Imóvel',
    '    Antes da locação, o imóvel deve apresentar condições adequadas de utilização e habitabilidade. Aspectos relacionados à segurança, instalações elétricas e hidráulicas, higiene, conservação e acessibilidade devem ser considerados pelas partes.',
    '    A vistoria inicial é particularmente relevante, pois documenta as condições em que o imóvel foi entregue e pode servir posteriormente como elemento de comparação no momento da devolução.',
    '2. Do locador',
    '    O locador possui obrigações relacionadas à disponibilização do imóvel em condições adequadas de uso e ao cumprimento das disposições legais e contratuais aplicáveis à relação locatícia.',
    '    Também é importante que a documentação relacionada ao imóvel e à própria contratação seja analisada adequadamente, bem como que sejam avaliadas as condições da pessoa que ocupará o bem.',
    '3. Do locatário',
    '    O locatário assume obrigações decorrentes do contrato, entre elas o pagamento pontual do aluguel e dos encargos que lhe sejam atribuídos, além da utilização e conservação do imóvel de acordo com o que foi convencionado.',
    '    Antes da contratação, é comum que sejam avaliadas capacidade financeira e garantias destinadas a reduzir os riscos decorrentes de eventual inadimplemento.',
    '4. Do contrato',
    '    O contrato de locação formaliza direitos e obrigações de locador e locatário e deve identificar adequadamente as partes, o imóvel, o valor do aluguel, os encargos, o prazo da locação e as demais condições estabelecidas entre os contratantes.',
    '    Nas locações urbanas, deve-se observar especialmente a Lei nº 8.245/1991, conhecida como Lei do Inquilinato.',
    '5. Da garantia',
    '    As garantias locatícias constituem importante mecanismo de proteção diante do risco de inadimplemento. A legislação prevê modalidades específicas, cuja utilização e efeitos devem ser avaliados conforme o contrato celebrado.',
    '    As condições da garantia devem ser claramente estabelecidas, inclusive quanto à sua vigência e às hipóteses em que poderá ser utilizada.',
    '6. Da inadimplência - riscos e prejuízos do locador',
    '    A falta de pagamento pode interromper uma fonte de receita do proprietário e ainda produzir despesas adicionais relacionadas à cobrança, manutenção do imóvel e eventual processo judicial.',
    '    O prolongamento da ocupação por locatário inadimplente também pode retardar uma nova locação e aumentar os prejuízos decorrentes da indisponibilidade do bem.',
    '7. Da inadimplência - riscos e prejuízos do locatário',
    '    Para o locatário, o inadimplemento pode resultar em cobrança do débito, incidência dos encargos contratualmente previstos e, presentes os requisitos legais, ação destinada à retomada do imóvel.',
    '    A negociação entre as partes pode ser considerada diante de dificuldades financeiras, sem prejuízo dos direitos e obrigações estabelecidos no contrato e na legislação.',
    '8. Quem sofre maior prejuízo imediato?',
    '    A inadimplência produz consequências para ambas as partes. Para o locador, entretanto, a interrupção do recebimento dos aluguéis pode produzir impacto financeiro imediato enquanto o imóvel continua indisponível para uma nova locação.',
    '    Para o locatário, podem surgir consequências patrimoniais, contratuais e processuais relacionadas à dívida e à permanência no imóvel.',
    '9. Como o locador pode mitigar seus prejuízos?',
    '    Entre as alternativas que podem ser avaliadas estão a negociação e cobrança extrajudicial, a utilização das garantias existentes e, quando necessária, a adoção das medidas judiciais previstas na legislação.',
    '    A medida adequada dependerá das circunstâncias concretas, da modalidade de garantia existente e das disposições do contrato.',
    '10. Ação de despejo: uma solução, ou um problema para o locador?',
    '    A ação de despejo constitui instrumento jurídico destinado à retomada do imóvel nas hipóteses previstas em lei. Apesar de possibilitar a recuperação da posse, o processo também pode envolver custos, prazos e discussão judicial.',
    '    Por isso, a escolha da estratégia deve considerar tanto o objetivo de recuperar o imóvel quanto os aspectos econômicos e processuais envolvidos.',
    '11. Ação de despejo: etapas legais',
    '    Conforme as circunstâncias, podem existir medidas extrajudiciais anteriores ou paralelas ao processo, incluindo comunicação formal ao locatário e tentativa de regularização da situação.',
    '    Persistindo o inadimplemento, a legislação prevê a possibilidade de ação de despejo por falta de pagamento, podendo haver também discussão sobre aluguéis e encargos devidos.',
    '    O procedimento judicial envolve a citação da parte contrária, oportunidade de defesa, apreciação judicial dos pedidos e posterior cumprimento da decisão.',
    '12. Uma "possível" solução "rápida": Liminar de Despejo',
    '    Em determinadas hipóteses previstas na Lei do Inquilinato, pode ser requerida medida liminar para desocupação do imóvel antes do julgamento definitivo da ação.',
    '    A concessão não é automática. Depende da hipótese legal invocada, dos elementos apresentados no processo e do preenchimento dos requisitos previstos em lei, cabendo ao juiz apreciar o pedido.',
    '13. Requisitos "mínimos" para a Liminar de Despejo',
    '    Os requisitos para uma medida liminar dependem do fundamento utilizado e das características da relação locatícia, inclusive da existência ou não das garantias previstas na legislação.',
    '    O artigo 59 da Lei nº 8.245/1991 disciplina hipóteses em que pode haver desocupação liminar, observados os requisitos legais correspondentes.',
    '14. E se o locatário se recusar a deixar o imóvel?',
    '    Uma ordem judicial de desocupação deve ser cumprida pelos meios processuais adequados. Havendo resistência, cabe ao Poder Judiciário determinar as providências necessárias para efetivação da decisão.',
    '    O proprietário não deve promover a retirada do ocupante por iniciativa própria à margem do procedimento legal.',
    '15. Ocorreu o despejo. O que o locador deve fazer?',
    '    Após a retomada do imóvel, é recomendável verificar seu estado de conservação e comparar as condições encontradas com aquelas documentadas anteriormente, especialmente por meio das vistorias realizadas.',
    '    Eventuais valores pendentes, danos ou encargos devem ser avaliados conforme o contrato, as garantias existentes e os instrumentos de cobrança juridicamente disponíveis.',
    'Conclusão',
    '    A inadimplência locatícia exige análise cuidadosa do contrato, das garantias e das circunstâncias concretas. A negociação pode solucionar determinadas situações, enquanto outras podem exigir medidas judiciais para cobrança dos débitos e retomada do imóvel.',
    '    A Lei do Inquilinato estabelece instrumentos específicos para a ação de despejo e, em determinadas hipóteses, admite pedido de desocupação liminar. A aplicação desses mecanismos depende do preenchimento dos requisitos legais de cada caso.',
    '    Por essa razão, medidas destinadas à retomada do imóvel devem observar o procedimento legal e as particularidades da relação contratual.',
    'Referências Bibliográficas',
    '    BRASIL. Lei nº 8.245, de 18 de outubro de 1991. Dispõe sobre as locações dos imóveis urbanos e os procedimentos a elas pertinentes.',
    '    BRASIL. Lei nº 10.406, de 10 de janeiro de 2002. Institui o Código Civil.',
    '    CARVALHO, Fabrício Bolzan de. Curso de Direito Imobiliário. 2. ed. São Paulo: Atlas, 2018.',
    '    COSTA, Karoline Lopes. Ação de despejo: vantagens e desvantagens para o locador. Revista Zênite, São Paulo, v. 244, p. 40-44, mar. 2014.',
    '    GUIMARÃES, M. C. A.; BANDEIRA, R. C. L. Locação de imóveis urbanos: aspectos legais e práticos. São Paulo: Editora Atlas, 2017.',
    '    GONÇALVES, Carlos Roberto. Direito civil brasileiro. São Paulo: Saraiva Educação, 2021. Vol. III.',
    '    NOGUEIRA, Guilherme Magalhães. Curso de Direito Imobiliário. 11. ed. São Paulo: Saraiva Educação, 2020.',
    '- o -',
    'FURLANI, Adilson. Inadimplência no contrato de aluguel - Como reaver o imóvel de forma rápida. Revista Jus Navigandi, ISSN 1518-4862, Teresina, ano 28, n. 7235, 23 abr. 2023. Disponível em: https://jus.com.br/artigos/103542.'
  ]
},
  {
  slug: 'educar-os-filhos-fora-da-escola',
  category: 'Direito à Educação',
  title: 'Educar os filhos fora da escola: é crime ou não?',
  excerpt: 'Análise sobre educação domiciliar, direito à educação e situações excepcionais envolvendo crianças com transtornos psicológicos que dificultam ou impedem a frequência escolar.',
  date: '11 abr. 2023',
  authorSlug: 'adilson-furlani',
  readTime: '10 min',
  body: [
    'Introdução',
    '    O direito à educação é um direito fundamental garantido pela Constituição Federal de 1988 e é considerado um instrumento essencial para o desenvolvimento individual e social. No entanto, a questão sobre a legalidade da educação domiciliar, também conhecida como homeschooling, tem gerado debates e controvérsias no Brasil. Além disso, a inclusão de crianças com transtornos psicológicos nas escolas públicas tem sido um desafio para o sistema educacional brasileiro.',
    '    A educação domiciliar consiste na modalidade de ensino em que os pais ou responsáveis assumem a responsabilidade pela educação dos filhos em casa, sem a necessidade de frequentar uma escola regular. Essa prática não é reconhecida pelo Estado brasileiro, pois a Constituição Federal e a Lei de Diretrizes e Bases da Educação (LDB) preveem a obrigatoriedade da educação escolar.',
    '    No entanto, há casos em que as crianças têm transtornos psicológicos que impedem sua participação na escola formal. Nesses casos, é preciso garantir o direito à educação por meio de medidas que atendam às necessidades específicas de cada criança.',
    '    A inclusão de crianças com transtornos psicológicos na escola pública é uma obrigação do Estado, que deve fornecer atendimento educacional especializado. O objetivo é garantir a inclusão social e a igualdade de oportunidades para essas crianças.',
    '    Para analisar a legalidade da educação domiciliar e o direito das crianças com transtornos psicológicos à educação pública, serão utilizadas referências bibliográficas atualizadas, como livros, artigos científicos e legislação pertinente.',
    '    Dentre as principais referências bibliográficas utilizadas estão a Constituição Federal de 1988, a LDB (Lei nº 9.394/96), o Estatuto da Criança e do Adolescente (Lei nº 8.069/90), a Convenção sobre os Direitos da Criança, a jurisprudência dos tribunais e a doutrina especializada.',
    '    Este artigo busca contribuir para o debate sobre a educação domiciliar e a inclusão de crianças com transtornos psicológicos na escola pública, a fim de garantir o pleno exercício do direito à educação para todas as crianças brasileiras.',
    '1. Legislação brasileira sobre a educação',
    '    É composta por diversas normas e leis que garantem o direito à educação e estabelecem as bases para a organização do sistema educacional brasileiro. A Constituição Federal de 1988, em seu artigo 6º, estabelece a educação como um direito social e dever do Estado, e a Lei de Diretrizes e Bases da Educação (LDB), Lei nº 9.394/96, regulamenta o sistema educacional brasileiro.',
    '    De acordo com a LDB, a educação escolar é obrigatória dos 4 aos 17 anos de idade e deve ser oferecida pela rede pública de ensino. A lei também estabelece que a educação é um direito de todos e dever do Estado, garantindo o acesso e permanência na escola. Além disso, a LDB prevê a oferta de atendimento educacional especializado para crianças com necessidades educacionais especiais, garantindo a inclusão dessas crianças na rede regular de ensino.',
    '    O Estatuto da Criança e do Adolescente (ECA), Lei nº 8.069/90, também garante o direito à educação e proteção integral à criança e ao adolescente. O ECA estabelece a obrigação do Estado de assegurar o acesso à educação pública e de qualidade, além de garantir a proteção contra todas as formas de discriminação.',
    '    A legislação brasileira garante o direito à educação como um direito fundamental, estabelecendo a obrigatoriedade da educação escolar e a oferta de atendimento educacional especializado para crianças com necessidades educacionais especiais. As famílias também têm direito a escolher a melhor forma de educação para seus filhos, desde que essa escolha esteja de acordo com a legislação educacional brasileira.',
    '2. Educação domiciliar',
    '    Também conhecida como homeschooling, é uma prática educativa em que os pais ou responsáveis se responsabilizam pela educação dos filhos em casa, sem a necessidade de frequentar uma escola regular. No Brasil, essa prática não é regulamentada por lei e, portanto, não é considerada legal.',
    '    O Supremo Tribunal Federal (STF) já se posicionou sobre o assunto em 2018, no julgamento da ADPF 461 e do RE 888.815, e decidiu que a educação domiciliar não é permitida no Brasil. Isso porque a Constituição Federal estabelece que a educação é um direito social e um dever do Estado, e a LDB prevê a obrigatoriedade da frequência à escola. Além disso, a educação domiciliar não permite a convivência com outras crianças e professores, o que é fundamental para a socialização e formação integral dos alunos.',
    '    No entanto, há casos em que a educação domiciliar pode ser autorizada pela Justiça, como em situações em que a criança possui alguma doença que impossibilita a frequência à escola ou quando a escola não consegue oferecer um ambiente adequado para a criança, especialmente aquelas com necessidades educacionais especiais.',
    '    Portanto, a educação domiciliar não é uma opção legal para as famílias brasileiras, mas pode ser autorizada em casos excepcionais, desde que comprovada a impossibilidade de frequência à escola e mediante autorização judicial.',
    '3. Exceções para a educação domiciliar',
    '    Ainda que a educação domiciliar não seja legal no Brasil, há exceções que permitem que as crianças recebam educação em casa. Uma dessas exceções é quando a criança possui transtornos psicológicos que impedem sua participação na escola formal.',
    '    Nesses casos, é preciso comprovar, por meio de laudos médicos e avaliações multidisciplinares, que a criança não tem condições de frequentar a escola regular. A autorização para a educação domiciliar deve ser concedida pela Justiça, que avaliará cada caso individualmente.',
    '    É importante ressaltar que a educação domiciliar não é a solução ideal para as crianças com transtornos psicológicos, pois a convivência com outros alunos e a presença de profissionais qualificados são fundamentais para o desenvolvimento social e emocional dessas crianças. Além disso, o acompanhamento da educação domiciliar pode ser um desafio para os pais, que muitas vezes não possuem a formação adequada para atuar como educadores em tempo integral.',
    '    Embora haja exceções que permitem a educação domiciliar para crianças com transtornos psicológicos, essa prática deve ser vista como uma solução temporária e sempre acompanhada de medidas para garantir a socialização e a integração dessas crianças na sociedade.',
    '4. A dificuldade das instituições públicas de ensino quanto a crianças com transtornos psicológicos',
    '    A inclusão de crianças com transtornos psicológicos no ambiente escolar pode representar um desafio para as instituições de ensino público. Segundo o Ministério da Educação (2018), as escolas devem estar preparadas para atender a diversidade dos alunos, inclusive aqueles com necessidades educacionais especiais. No entanto, muitas vezes a realidade é diferente, e as escolas encontram dificuldades para oferecer um ensino adequado a esses alunos.',
    '    Uma pesquisa realizada por Aquino e Zago (2018) com 13 escolas públicas de São Paulo que atendiam crianças com transtornos psicológicos identificou que as principais dificuldades encontradas foram a falta de capacitação dos professores para lidar com esses alunos, a falta de recursos materiais e financeiros para atender às necessidades especiais e a falta de apoio da família.',
    '    Além disso, as escolas muitas vezes não estão preparadas para lidar com a complexidade dos transtornos psicológicos, o que pode levar a situações de discriminação e exclusão social.',
    '    É importante ressaltar que a inclusão escolar não se resume apenas à matrícula do aluno em uma escola regular, mas sim à garantia de um ambiente educacional adequado e inclusivo, que atenda às suas necessidades individuais.',
    '    Nesse sentido, é papel das escolas públicas e do Estado como um todo oferecer condições para que as crianças com transtornos psicológicos tenham acesso à educação, com estrutura e recursos adequados, além de oferecer formação e capacitação aos professores para lidar com esses alunos de forma efetiva.',
    '5. Direitos das crianças com transtornos psicológicos',
    '    As crianças com transtornos psicológicos possuem o direito à educação pública garantido pela Constituição Federal e pela Lei de Diretrizes e Bases da Educação Nacional. O artigo 208 da Constituição Federal estabelece que o Estado deve garantir o atendimento educacional especializado aos portadores de deficiência, preferencialmente na rede regular de ensino. Já a Lei nº 9.394/96 prevê que a educação especial é uma modalidade de educação escolar, oferecida preferencialmente na rede regular de ensino.',
    '    Além disso, as escolas devem adotar medidas para garantir a inclusão dessas crianças, como a adaptação do ambiente escolar, o acompanhamento por profissionais especializados e o fornecimento de recursos pedagógicos adequados. As escolas também devem promover a sensibilização da comunidade escolar sobre as necessidades dessas crianças e garantir que elas sejam tratadas com respeito e dignidade.',
    '    É importante ressaltar que o cumprimento dessas medidas é fundamental para que as crianças com transtornos psicológicos possam ter acesso à educação de qualidade e desenvolver todo o seu potencial. Além disso, a inclusão dessas crianças na sociedade é um direito humano básico e um princípio fundamental da democracia.',
    '6. Responsabilidade dos pais',
    '    Os pais são responsáveis por garantir a educação de seus filhos, seja por meio da matrícula em escolas regulares, por meio da educação domiciliar ou por meio de outras modalidades de ensino. No caso das crianças com transtornos psicológicos, essa responsabilidade se torna ainda mais importante, já que elas podem enfrentar maiores dificuldades para acessar a educação formal.',
    '    Cabe aos pais buscar alternativas e recursos que possam contribuir para a inclusão e o desenvolvimento educacional de seus filhos, como o acompanhamento de profissionais especializados, a adaptação do ambiente domiciliar para o aprendizado e o uso de materiais e recursos pedagógicos adequados.',
    '    No entanto, é importante ressaltar que a responsabilidade dos pais não se sobrepõe ao direito à educação garantido às crianças pela Constituição Federal e pelas leis brasileiras. Os pais não podem impedir o acesso de seus filhos à educação formal por razões de crença religiosa ou por preferência pessoal.',
    '7. Jurisprudência sobre a educação domiciliar',
    '    A jurisprudência brasileira em relação à educação domiciliar é um tema em constante evolução, uma vez que a prática ainda é relativamente nova no país e vem sendo alvo de discussões e questionamentos. Atualmente, a educação domiciliar é considerada ilegal no Brasil, uma vez que não é reconhecida pela legislação nacional.',
    '    No entanto, há casos em que as famílias recorrem à justiça para garantir o direito de educar seus filhos em casa, especialmente em situações em que a criança apresenta transtornos psicológicos que impedem sua participação na escola formal. A jurisprudência em relação a esses casos tem sido variável, com algumas decisões favoráveis à educação domiciliar e outras que negam o pedido das famílias.',
    '    É importante ressaltar que, até o momento, a jurisprudência em relação à educação domiciliar no Brasil ainda é pouco consolidada e está em constante mudança. Cabe às famílias interessadas na prática buscar orientação jurídica e avaliar os riscos e benefícios envolvidos antes de tomar qualquer decisão.',
    '8. O papel do Estado',
    '    O Estado brasileiro tem a obrigação de garantir o direito à educação para todas as crianças, incluindo aquelas com transtornos psicológicos que precisam de atendimento educacional especializado. A Constituição Federal de 1988, em seu artigo 208, estabelece que o dever do Estado com a educação será efetivado mediante a garantia de atendimento educacional especializado aos portadores de deficiência, preferencialmente na rede regular de ensino.',
    '    Além disso, a Lei de Diretrizes e Bases da Educação Nacional (Lei nº 9.394/96) define que é dever do Estado garantir educação especial para pessoas com deficiência, preferencialmente na rede regular de ensino. Para isso, as escolas devem oferecer recursos e serviços de apoio pedagógico adequados às necessidades dos estudantes com deficiência, incluindo recursos de acessibilidade e atendimento educacional especializado.',
    '    O Estado também deve garantir o acesso das crianças com transtornos psicológicos aos serviços de saúde mental, que muitas vezes são essenciais para o sucesso educacional dessas crianças. Além disso, o Estado deve fornecer treinamento adequado aos professores e profissionais da educação para que eles possam atender adequadamente as necessidades educacionais dessas crianças.',
    'Conclusão',
    '    A educação é um direito fundamental garantido pela Constituição brasileira e todas as crianças têm o direito de receber educação de qualidade. No entanto, para crianças com transtornos psicológicos, pode ser um desafio garantir que elas recebam educação inclusiva e adequada.',
    '    A legislação brasileira estabelece a educação domiciliar como uma exceção à educação formal, mas com limitações e regras específicas. É necessário um esforço conjunto do Estado, das escolas e das famílias para garantir que as crianças com transtornos psicológicos recebam educação adequada. As famílias devem ter o direito de escolher a melhor opção de educação para seus filhos, desde que sejam respeitados os direitos e as obrigações legais.',
    '    É importante que as escolas tenham recursos adequados para receber crianças com transtornos psicológicos e oferecer educação inclusiva, como salas de aula adaptadas, professores qualificados e suporte emocional e psicológico. As políticas públicas devem ser desenvolvidas para garantir que todas as crianças tenham acesso à educação de qualidade, independentemente de suas condições de saúde.',
    '    A jurisprudência brasileira sobre a educação domiciliar ainda é incipiente, mas tem sido discutida com mais frequência nos tribunais. É fundamental que a legislação sobre o tema seja atualizada para garantir que as famílias e as crianças tenham seus direitos e deveres claramente definidos.',
    '    Por fim, a educação é um direito fundamental e deve ser garantida para todas as crianças, inclusive aquelas com transtornos psicológicos. As famílias devem ter o direito de escolher a melhor opção de educação para seus filhos, mas sempre seguindo as regras estabelecidas pela legislação brasileira.',
    '    As escolas e o Estado devem trabalhar juntos para garantir que as crianças recebam educação inclusiva e adequada, proporcionando as condições necessárias para que elas possam se desenvolver plenamente e realizar seu potencial.',
    'Referências Bibliográficas',
    '    AQUINO, J. L. G.; ZAGO, N. Estudo sobre escolas públicas que atendem alunos com transtornos psicológicos. Psicologia Escolar e Educacional, v. 22, n. 3, p. 433-441, 2018.',
    '    BRASIL. Constituição Federal, 1988. Acesso em 10 abr. 2023.',
    '    BRASIL. Estatuto da Criança e do Adolescente, Lei nº 8.069, de 13 de julho de 1990. Acesso em 07 abr. 2023.',
    '    BRASIL. Lei de Diretrizes e Bases da Educação Nacional, Lei nº 9.394, de 20 de dezembro de 1996. Acesso em 07 abr. 2023.',
    '    BRASIL. Lei nº 13.005, de 25 de junho de 2014. Aprova o Plano Nacional de Educação — PNE e dá outras providências.',
    '    BRASIL. Ministério da Educação. Secretaria de Educação Especial. Política Nacional de Educação Especial na Perspectiva da Educação Inclusiva. Brasília, DF: MEC/SEESP, 2008.',
    '    BRASIL. Superior Tribunal de Justiça. REsp 1.395.702 - RS (2013/0098567-6). Acesso em 08 abr. 2023.',
    '    BRASIL. Supremo Tribunal Federal. Ação Direta de Inconstitucionalidade nº 5.357. Brasília, DF, 8 de setembro de 2016.',
    '    BRASIL. Tribunal de Justiça do Estado de São Paulo. Apelação nº 1000316-45.2019.8.26.0566. São Paulo, 28 de janeiro de 2020.',
    '    FERREIRA, Naura Syria Carapeto; AGUIAR, Márcia Ângela da S. Amaral; GARCIA, Regina Leite (Orgs.). Gestão da educação: impasses, perspectivas e compromissos. São Paulo: Cortez, 2000.',
    '    FREIRE, Marcelo. Educação domiciliar: perspectivas e desafios no Brasil. Rio de Janeiro: WAK, 2018.',
    '    SANTOS, Maria Lúcia de A. Educação Inclusiva: concepções e práticas. São Paulo: Cortez, 2004.',
    '    GADOTTI, Moacir. História das ideias pedagógicas. São Paulo: Ática, 1998.',
    '    SUPREMO TRIBUNAL FEDERAL. ADPF 461. Acesso em 09 abr. 2023.',
    '    SUPREMO TRIBUNAL FEDERAL. RE 888.815. Acesso em 09 abr. 2023.',
    '- o -',
    'FURLANI, Adilson. Educar os filhos fora da escola: é crime ou não?. Revista Jus Navigandi, ISSN 1518-4862, Teresina, ano 28, n. 7223, 11 abr. 2023. Disponível em: https://jus.com.br/artigos/103491.'
  ]
},
];

export const reviews = [
  { author:'Cliente Google 01', text:'Excelente atendimento. Equipe muito preparada e sempre disponível para esclarecer nossas dúvidas.', source:'Google', url:process.env.NEXT_PUBLIC_GOOGLE_REVIEWS_URL || '#' },
  { author:'Cliente Google 02', text:'Profissionais atenciosos, técnicos e claros na condução das questões.', source:'Google', url:process.env.NEXT_PUBLIC_GOOGLE_REVIEWS_URL || '#' },
];
