export type Area = { slug:string; title:string; summary:string; intro:string; services:string[]; approach:string };
export type Lawyer = { slug:string; name:string; role:string; oab:string; areas:string[]; education:string[]; bio:string; publications:string[] };
export type Article = { slug:string; category:string; title:string; excerpt:string; date:string; authorSlug:string; readTime:string; body:string[] };

export const areas: Area[] = [
  { slug:'direito-tributario', title:'Direito Tributário', summary:'Assessoria e atuação em questões tributárias administrativas e judiciais.', intro:'Atuação jurídica em questões tributárias que exigem análise técnica, visão estratégica e compreensão do ambiente empresarial.', services:['Planejamento tributário','Análise de questões fiscais','Consultoria tributária','Recuperação de créditos','Processos administrativos','Processos judiciais','Análise de riscos tributários','Acompanhamento de mudanças legislativas'], approach:'Cada questão tributária é analisada considerando o contexto jurídico, econômico e operacional envolvido, com identificação de riscos, alternativas e caminhos juridicamente adequados.' },
  { slug:'direito-empresarial', title:'Direito Empresarial', summary:'Estratégias jurídicas alinhadas às necessidades e ao contexto de cada negócio.', intro:'Assessoria jurídica para decisões empresariais, estruturas societárias e situações que exigem integração entre direito e negócio.', services:['Consultoria empresarial','Questões societárias','Governança','Reorganizações','Negociações','Prevenção de conflitos'], approach:'A atuação considera os objetivos do negócio, os riscos envolvidos e as alternativas juridicamente disponíveis para cada decisão.' },
  { slug:'contratos', title:'Contratos', summary:'Análise, elaboração, negociação e revisão de instrumentos contratuais.', intro:'Estruturação contratual com atenção à clareza, alocação de riscos e aderência à operação das partes.', services:['Elaboração de contratos','Revisão contratual','Negociação','Contratos empresariais','Instrumentos de garantia','Gestão de riscos contratuais'], approach:'Os instrumentos são desenvolvidos a partir da realidade da operação, buscando clareza, coerência e previsibilidade jurídica.' },
  { slug:'contencioso', title:'Contencioso', summary:'Atuação técnica na condução de demandas judiciais e administrativas.', intro:'Condução estratégica de conflitos com análise de risco, definição de teses e acompanhamento próximo da evolução de cada demanda.', services:['Contencioso cível','Contencioso empresarial','Processos administrativos','Estratégia processual','Negociação e acordos','Gestão de carteira'], approach:'Cada demanda é analisada de forma individualizada, considerando fundamentos jurídicos, evidências, riscos e possíveis desdobramentos.' },
  { slug:'consultoria-juridica', title:'Consultoria Jurídica', summary:'Análise preventiva de questões jurídicas e identificação de alternativas.', intro:'Apoio jurídico contínuo para decisões que demandam prevenção, estruturação e avaliação de riscos.', services:['Pareceres','Consultas jurídicas','Mapeamento de riscos','Apoio a decisões','Políticas internas','Prevenção de litígios'], approach:'A consultoria transforma questões jurídicas em informações claras para apoiar decisões responsáveis e documentadas.' },
  { slug:'regulatorio', title:'Regulatório', summary:'Apoio jurídico em temas regulatórios e ambientes normativos complexos.', intro:'Assessoria em ambientes regulados, com acompanhamento de normas, riscos e obrigações aplicáveis às operações.', services:['Análise regulatória','Acompanhamento normativo','Consultas e pareceres','Mapeamento de obrigações','Apoio institucional'], approach:'O trabalho parte da leitura técnica da regulação e de seus impactos concretos sobre processos, produtos e decisões empresariais.' },
];

export const lawyers: Lawyer[] = [
  { slug:'joao-da-silva', name:'João da Silva', role:'Sócio', oab:'OAB/SP 00.001', areas:['Direito Tributário','Direito Empresarial'], education:['Bacharel em Direito — Universidade X','Pós-graduação em Direito Tributário — Universidade Y'], bio:'Atua em questões consultivas e contenciosas relacionadas ao ambiente empresarial, com experiência na análise de temas tributários e estratégicos.', publications:['Reforma Tributária: principais pontos para empresas','Planejamento e segurança jurídica nas decisões empresariais'] },
  { slug:'mariana-souza', name:'Mariana Souza', role:'Sócia', oab:'OAB/SP 00.002', areas:['Direito Empresarial','Contratos'], education:['Bacharel em Direito — Universidade X','Pós-graduação em Direito Empresarial — Universidade Z'], bio:'Atua na estruturação de relações empresariais, negociação e revisão de contratos e apoio jurídico a decisões de negócio.', publications:['Cláusulas contratuais que merecem atenção','Governança e prevenção de conflitos societários'] },
  { slug:'pedro-almeida', name:'Pedro Almeida', role:'Advogado', oab:'OAB/SP 00.003', areas:['Contencioso','Consultoria Jurídica'], education:['Bacharel em Direito — Universidade X'], bio:'Atua na condução de demandas judiciais e administrativas, com foco em análise processual, organização de evidências e acompanhamento estratégico.', publications:['Decisões empresariais e análise jurídica preventiva'] },
];

export const articles: Article[] = [
  { slug:'reforma-tributaria-principais-pontos-empresas', category:'Tributário', title:'Reforma Tributária: principais pontos para empresas', excerpt:'Uma visão objetiva sobre temas que merecem acompanhamento na adaptação ao novo ambiente tributário.', date:'12 set. 2026', authorSlug:'joao-da-silva', readTime:'6 min', body:['A Reforma Tributária altera de forma relevante a lógica de tributação sobre o consumo e exige atenção das empresas durante o período de transição.','Mais do que acompanhar mudanças legislativas, é importante mapear os impactos sobre contratos, precificação, sistemas, processos internos e relacionamento com fornecedores e clientes.','A avaliação jurídica deve ser integrada às áreas financeira, fiscal e operacional, de modo que as decisões sejam tomadas com base em informações consistentes e atualizadas.','Este conteúdo possui caráter exclusivamente informativo e não constitui aconselhamento jurídico individualizado.'] },
  { slug:'analise-juridica-preventiva-decisoes-empresariais', category:'Empresarial', title:'Decisões empresariais e a importância da análise jurídica preventiva', excerpt:'Como a leitura antecipada de riscos pode apoiar decisões mais estruturadas.', date:'05 set. 2026', authorSlug:'pedro-almeida', readTime:'5 min', body:['A análise jurídica preventiva busca identificar riscos antes que eles se convertam em conflitos ou custos inesperados.','Em decisões empresariais relevantes, a participação jurídica desde as etapas iniciais pode contribuir para estruturar documentos, responsabilidades e mecanismos de prevenção de controvérsias.','A prevenção não elimina incertezas, mas permite que elas sejam identificadas e tratadas de maneira organizada.','Este conteúdo possui caráter exclusivamente informativo e não constitui aconselhamento jurídico individualizado.'] },
  { slug:'clausulas-contratuais-atencao-especial', category:'Contratos', title:'Cláusulas contratuais que merecem atenção especial', excerpt:'Pontos que ajudam a tornar a relação contratual mais clara e previsível.', date:'28 ago. 2026', authorSlug:'mariana-souza', readTime:'7 min', body:['Contratos eficientes devem refletir a operação real das partes e distribuir responsabilidades de forma compreensível.','Cláusulas sobre objeto, pagamento, responsabilidade, rescisão, confidencialidade e solução de conflitos costumam merecer atenção especial.','A qualidade de um contrato não depende apenas de sua extensão, mas da clareza com que antecipa situações relevantes para aquela relação.','Este conteúdo possui caráter exclusivamente informativo e não constitui aconselhamento jurídico individualizado.'] },
];

export const reviews = [
  { author:'Cliente Google 01', text:'Excelente atendimento. Equipe muito preparada e sempre disponível para esclarecer nossas dúvidas.', source:'Google', url:process.env.NEXT_PUBLIC_GOOGLE_REVIEWS_URL || '#' },
  { author:'Cliente Google 02', text:'Profissionais atenciosos, técnicos e claros na condução das questões.', source:'Google', url:process.env.NEXT_PUBLIC_GOOGLE_REVIEWS_URL || '#' },
];
